"""add updated_at

Revision ID: cfffe424545e
Revises: 0001
Create Date: 2026-06-28 03:33:50.565074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfffe424545e'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_relationships', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_rel_org'), table_name='asset_relationships')
    op.create_index(op.f('ix_asset_relationships_org_id'), 'asset_relationships', ['org_id'], unique=False)
    op.add_column('assets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_asset_org_id'), table_name='assets')
    op.create_index(op.f('ix_assets_org_id'), 'assets', ['org_id'], unique=False)
    op.add_column('import_jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('import_jobs', 'total',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'imported',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_job_org'), table_name='import_jobs')
    op.create_index(op.f('ix_import_jobs_org_id'), 'import_jobs', ['org_id'], unique=False)
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_org_slug'), table_name='organizations')
    op.drop_constraint(op.f('uq_org_slug'), 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_user_email'), table_name='users')
    op.drop_index(op.f('ix_user_org'), table_name='users')
    op.drop_constraint(op.f('uq_user_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('uq_user_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_org'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'updated_at')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_unique_constraint(op.f('uq_org_slug'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_org_slug'), 'organizations', ['slug'], unique=False)
    op.drop_column('organizations', 'updated_at')
    op.drop_index(op.f('ix_import_jobs_org_id'), table_name='import_jobs')
    op.create_index(op.f('ix_job_org'), 'import_jobs', ['org_id'], unique=False)
    op.alter_column('import_jobs', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'imported',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'total',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('import_jobs', 'updated_at')
    op.drop_index(op.f('ix_assets_org_id'), table_name='assets')
    op.create_index(op.f('ix_asset_org_id'), 'assets', ['org_id'], unique=False)
    op.drop_column('assets', 'updated_at')
    op.drop_index(op.f('ix_asset_relationships_org_id'), table_name='asset_relationships')
    op.create_index(op.f('ix_rel_org'), 'asset_relationships', ['org_id'], unique=False)
    op.drop_column('asset_relationships', 'updated_at')
    # ### end Alembic commands ###
